CREATE TABLE newtable (LIKE customer);

INSERT INTO newtable
    SELECT *
        FROM CUSTOMER
        WHERE C_CUSTKEY NOT IN (SELECT DISTINCT O_CUSTKEY FROM ORDERS);


--lub

CREATE TABLE customer_no_orders AS
    SELECT *
        FROM CUSTOMER
        WHERE C_CUSTKEY NOT IN (SELECT DISTINCT O_CUSTKEY FROM ORDERS);
