-- Stworzenie tabeli z archiwum
CREATE TABLE offer_archive (
    title text COLLATE pg_catalog."default",
    marker_icon text COLLATE pg_catalog."default",
    workplace_type text COLLATE pg_catalog."default",
    experience_level text COLLATE pg_catalog."default",
    published_at text COLLATE pg_catalog."default",
    remote_interview boolean,
    id_jjit text COLLATE pg_catalog."default",
    remote boolean,
    if_permanent boolean,
    salary_from_permanent text COLLATE pg_catalog."default",
    salary_to_permanent text COLLATE pg_catalog."default",
    salary_currency_permanent text COLLATE pg_catalog."default",
    if_b2b boolean,
    salary_from_b2b text COLLATE pg_catalog."default",
    salary_to_b2b text COLLATE pg_catalog."default",
    salary_currency_b2b text COLLATE pg_catalog."default",
    if_mandate boolean,
    salary_from_mandate text COLLATE pg_catalog."default",
    salary_to_mandate text COLLATE pg_catalog."default",
    salary_currency_mandate text COLLATE pg_catalog."default",
    currency_exchange_rate text COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company_id integer NOT NULL,
    company_branch_id integer NOT NULL,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Funkcja triggerowa (brzydka ale najprostsza opcja)
CREATE OR REPLACE FUNCTION archive_deleted_offer()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO offer_archive
    SELECT OLD.*;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Trigger
CREATE TRIGGER offer_delete_trigger
BEFORE DELETE ON offer
FOR EACH ROW
EXECUTE FUNCTION archive_deleted_offer();

-- Przerabiamy constrainty tak jak na poprzednich labach
ALTER TABLE skill
DROP CONSTRAINT skill_offer_id_fkey;

ALTER TABLE skill add CONSTRAINT skill_offer_id_fkey FOREIGN KEY (offer_id)
        REFERENCES public.offer (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE;

-- i możemy usuwać i działa
select * from offer;
delete from offer where id = 2;
select * from offer_archive;

-- Przechowuję w osobnej tabeli
-- Można też w tej samej tabeli -> wtedy dodajemy odp. kolumny